var data = [
{name:"Juls",one:"6922454647",bgcolor:"123456",color:"white",message:"abcdefgwdqpoddkpwkdwdpwdkw;wldwkdwdwqweqweoqdjisadiodldkwdjouasxhduwdqhduqfhewfuwfowwieofjdwedjwdlwkfjwlwekdw"},

{name:"Kiana",one:"1315904529",bgcolor:"6699ff",color:"black",message:"You are one of my most precious moots <3 You light up my day like the sun; it's never complete without seeing you on my tl. Thank you for listening to me at my lowest points, and I'm thankful as well for the moments we shared along the way. I hope you're doing well always. May 2021 be better for both of us!!!! Take care of yourself everyday, bb! *orange heart*"},

{name:"Lyn",one:"6842349839",bgcolor:"004c64",color:"white",message:"Hanggang ngayon, never ko talagang akalain na magiging super close tayo. Nagsimula lang sa simpleng tanong lang tungkol sa UPCAT tapos anlaki ng na-grow sa pagsasama natin. Also, I really love your art style, if you plan on reopening commissions, I'll do my best to support! Btw, it's funny na hindi pa tayo nagkikita in person, pero I hope that changes soon! Let's hope na magiging mas maganda ang 2021 para satin."},

{name:"Robina",one:"4699734352",bgcolor:"8e1d39",color:"white",message:"I'm really grateful na naging magkaklase tayo last year. Not only that, marami na tayong pinagsamahan from class prods hanggang sa mga random kong kwento. Thank you talaga sa pakikinig sakin, and for being there whenever nagkaka-breakdown ako sa klase. Sana mas magiging mabuti ang 2021 satin, and sana makagawa tayo ng mas maraming good memories! Btw, hindi pa tapos yung nobela na sinusulat ko HAHAHAHAHA"},

{name:"Miggy",one:"2456456828",bgcolor:"fce3aa",color:"black",message:"Ikaw yung isa sa mga pinakapaborito tong tao, seriously. Online man lang yung way of communication natin ngayon, walang nagbago sa friendship natin in corona times. Sa face to face man, never kong makakalimutan yung mga small moments natin, whether katarantaduhan or nagpapatulong ka sa akin. Thank you dahil pinapakinggan mo yung vents ko kahit minsan nakakasawa. Namiss ko na tuloy makipagmilk tea kasama kita, sana maulit :(((( Ingat palagi tols!"},

{name:"Tom",one:"7738419006",bgcolor:"a99a93",color:"black",message:"Bruh, we've been close for just some time pero andami na nating productive stuff na nagawa sa isa't isa, lalo na dahil magkaklase tayo this year. I promise, malayo ang mararating natin in the future when we do more things sa klase. Tandaan mo lang na if ever you need help sa isang bagay, I'm just one message away. Thank you talaga kasi kahit kadalasan sa discord lang tayo ay kahit papaano I was less alone this year. Ingat ka palagi mehn :')"},

{name:"Kuya Joshua",one:"1884845130",bgcolor:"6b41af",color:"white",message:"Kuya, thank you talaga for helping me become closer kay God. 2020 has been one of the toughest years of my life, pero kahit papaano ay na-ease yung loneliness ko dahil sa mga video chats natin na very worthwhile at memorable. I hope na 2021 will be better for both of us, at sana magkita man tayo in person soon :(((( Good luck po sa college life, and always take care wherever you are!!!"},

{name:"Rafa",one:"8958450136",bgcolor:"5d9481",color:"black",message:"Despite the coronavirus pandemic, naging matatag parin ang friendship natin, and I highly treasure that. Even though these times are rough, our convos eased the struggle a bit. Alam mo, sana magkaroon na tayo ng state visit next year, sabay magkakalat lang tayo eh noh HAHAHAHAHAHA Also, keep up sa Dutch mo, I don't know how to say 'kaya mo yan' pero you get the point. We got through 2020 together, let's hope na 2021 will be better for us!"},

{name:"Pansy",one:"2437574636",bgcolor:"59535d",color:"white",message:"You are a big part of why I appreciate studytwt so much. I really love your tweets, especially your passion to speak up for matters you care about. I'll never forget every dm we've had over any topic. You're one of the most amazing people I've met in this community! Please take care of yourself always, and remember that there are a lot of people who believe in you, and that includes me. Te amo mucho Pansy!"},

{name:"Nathan",one:"4480232941",bgcolor:"f6dfab",color:"black",message:"Boi maraming salamat talaga kasi even though mahirap i-cope ang covid, you're one of those na nagpapagaan sa mga mabibigat na times katulad ngayon. Even though you're a lasallian na and puro discord at messenger lang interactions these days, I love it na masaya and meaningful pa rin ang mga pag-uusap natin. I believe na makakamit mo yung mga pangarap mo balang-araw, magtiwala ka lang :))) Arat wako de go pag wala nang corona"},

{name:"Ysaac",one:"5488155702",bgcolor:"fdefd5",color:"black",message:"Sana naenjoy mo yung potato chips HAHAHAHA Thank you kasi kahit may pandemya, naging malakas pa rin ang pagsasama natin kahit online man lang. Namiss ko tuloy pagsesetup natin tuwing break o di kaya pag hindi tayo masyadong busy. Sana magkita tayo ulit after the pandemic! I'm grateful din dahil isa ka sa mga mapagkakatiwalaan ko. Magiging maganda ang 2021, claiming it!!!"},

{name:"Haddie",one:"7262654634",bgcolor:"7f8180",color:"black",message:"BB, kung hindi dahil sayo, hindi kumpleto ang studytwt experience ko. I'm still amazed as to how nacocope mo yung pagkakalat ko tungkol kay [REDACTED] HAHAHAHAHA Pero on the serious side, thank you for being a good friend sa akin. Thank you kasi you're one of those people who I can trust kahit never pa tayo nagkita irl. Also, I have high hopes na makakamit mo lahat ng pangarap mo sa buhay :)))) LUV U BB!!!!!"}

];